artifacts_config:
  artifacts_dir: artifacts

data_ingestion_config:
  dataset_download_url: https://github.com/varshagandhi-01/DataScience/raw/refs/heads/main/books_data.zip
  dataset_dir: dataset
  ingested_dir: ingested_data
  raw_data_dir: raw_data

data_validation_config:
  clean_data_dir: clean_data
  serialized_objects_dir: serialized_objects
  books_csv_file: BX-Books.csv
  ratings_csv_file: BX-Book-Ratings.csv 

data_transformation_config:
  transformed_data_dir: transformed_data 
  

  


